apiVersion: 1

datasources:
  - name: Solar MPPT
    uid: influxdb-solar
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mppt
      defaultBucket: solar
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
    editable: false

  - name: Solar MPPT - History
    uid: influxdb-solar-history
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mppt
      defaultBucket: solar_history
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: false
