# Protobuf schema and generated Python binding
#
# mppt.proto:      source-of-truth schema
# mppt_pb2.py:     generated by `make proto` inside parser/
#
# The simulator (parser/test/mppt_simulator.py) adds the repo root to sys.path automatically
