/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "mppt.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mppt_DeviceInfo, mppt_DeviceInfo, AUTO)


PB_BIND(mppt_FaultStatus, mppt_FaultStatus, AUTO)


PB_BIND(mppt_Telemetry, mppt_Telemetry, AUTO)


PB_BIND(mppt_DeviceSettings, mppt_DeviceSettings, AUTO)


PB_BIND(mppt_LogEntry, mppt_LogEntry, AUTO)


PB_BIND(mppt_DataloggerPayload, mppt_DataloggerPayload, AUTO)


PB_BIND(mppt_ControlCommand, mppt_ControlCommand, AUTO)


PB_BIND(mppt_ClearDatalogger, mppt_ClearDatalogger, AUTO)


PB_BIND(mppt_SwitchLoad, mppt_SwitchLoad, AUTO)


PB_BIND(mppt_CommandAck, mppt_CommandAck, AUTO)


PB_BIND(mppt_DeviceSnapshot, mppt_DeviceSnapshot, AUTO)


PB_BIND(mppt_FleetSummary, mppt_FleetSummary, AUTO)













