[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino@^2.5.0
    nanopb/Nanopb@^0.4.91
build_flags = 
    -DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
    -DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
    -DCORE_DEBUG_LEVEL=3
